# Generated by Django 2.2.5 on 2020-01-09 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200109_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_crud_book', 'CRUD book'),)},
        ),
    ]
